"use client";

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination, Keyboard } from 'swiper/modules';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

interface MediaCarouselProps {
  media: string[];
  coverMedia: string;
  projectTitle: string;
}

export default function MediaCarousel({ media, coverMedia, projectTitle }: MediaCarouselProps) {
  const [initialSlide, setInitialSlide] = useState(0);

  // Helper function to check if media is video
  const isVideo = (mediaPath: string) => {
    return mediaPath.endsWith('.mp4') || mediaPath.endsWith('.mov') || mediaPath.endsWith('.webm');
  };

  // Find the index of coverMedia to start the carousel there
  useEffect(() => {
    const coverIndex = media.findIndex(item => item === coverMedia);
    setInitialSlide(coverIndex >= 0 ? coverIndex : 0);
  }, [media, coverMedia]);

  return (
    <div className="w-full max-w-4xl mx-auto px-2 sm:px-0">
      <Swiper
        slidesPerView={1}
        spaceBetween={10}
        centeredSlides={true}
        loop={media.length > 1}
        initialSlide={initialSlide}
        navigation={{
          nextEl: '.swiper-button-next-custom',
          prevEl: '.swiper-button-prev-custom',
        }}
        pagination={{
          clickable: true,
          el: '.swiper-pagination-custom',
        }}
        keyboard={{
          enabled: true,
        }}
        modules={[Navigation, Pagination, Keyboard]}
        className="relative"
      >
        {media.map((mediaItem, index) => (
          <SwiperSlide key={index}>
            <div className="relative w-full h-[250px] sm:h-[350px] lg:h-[500px] overflow-hidden">
              {isVideo(mediaItem) ? (
                <video
                  className="w-full h-full object-contain"
                  controls
                  muted
                  playsInline
                  preload="metadata"
                >
                  <source src={mediaItem} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
              ) : (
                <Image
                  src={mediaItem}
                  alt={`${projectTitle} media ${index + 1}`}
                  fill
                  className="object-contain"
                  sizes="(max-width: 768px) 95vw, 80vw"
                />
              )}
            </div>
          </SwiperSlide>
        ))}
      </Swiper>

      {/* Custom Navigation Buttons */}
      {media.length > 1 && (
        <>
          <button className="swiper-button-prev-custom absolute left-2 sm:left-4 top-1/2 -translate-y-1/2 z-10 w-8 h-8 sm:w-10 sm:h-10 bg-black/20 hover:bg-black/40 rounded-full shadow-lg flex items-center justify-center transition-all duration-200 hover:scale-110 backdrop-blur-sm">
            <svg className="w-4 h-4 sm:w-5 sm:h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          
          <button className="swiper-button-next-custom absolute right-2 sm:right-4 top-1/2 -translate-y-1/2 z-10 w-8 h-8 sm:w-10 sm:h-10 bg-black/20 hover:bg-black/40 rounded-full shadow-lg flex items-center justify-center transition-all duration-200 hover:scale-110 backdrop-blur-sm">
            <svg className="w-4 h-4 sm:w-5 sm:h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </>
      )}

      {/* Custom Pagination */}
      {media.length > 1 && (
        <div className="swiper-pagination-custom flex justify-center space-x-2 mt-4 sm:mt-6">
          {/* Pagination dots will be generated by Swiper */}
        </div>
      )}

      <style jsx>{`
        :global(.swiper-pagination-custom .swiper-pagination-bullet) {
          width: 8px;
          height: 8px;
          background: #cbd5e0;
          opacity: 1;
          border-radius: 50%;
          transition: all 0.3s ease;
        }

        :global(.swiper-pagination-custom .swiper-pagination-bullet-active) {
          background: #2d3748;
          transform: scale(1.2);
        }

        @media (max-width: 640px) {
          :global(.swiper-pagination-custom .swiper-pagination-bullet) {
            width: 6px;
            height: 6px;
          }
        }
      `}</style>
    </div>
  );
} 